module.exports = {
  sidebar: [
    // ============================================
    // WELCOME
    // ============================================
    "homepage/welcome",

    // ============================================
    // GETTING STARTED (Role-based)
    // ============================================
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/for-experiment-owners",
        "getting-started/for-data-scientists",
        "getting-started/for-engineers",
        "getting-started/for-reviewers",
        "getting-started/for-leadership",
        "getting-started/for-contributors"
      ]
    },

    // ============================================
    // EXPERIMENT WORKFLOW
    // ============================================
    {
      type: "category",
      label: "Experiment Workflow",
      items: [
        "workflow/overview",
        "workflow/experimenter-console",
        "workflow/designing",
        "advanced/rollouts-deep-dive",
        "workflow/configuring",
        "workflow/localization",
        {
          type: "category",
          label: "Testing & QA",
          items: [
            "workflow/testing",
            "platform-guides/desktop/desktop-feature-api-testing",
            "platform-guides/android/android-preview-testing",
            "platform-guides/ios/ios-preview-testing"
          ]
        },
        "workflow/risk-mitigation",
        "workflow/launching",
        "workflow/monitoring",
        "workflow/analyzing",
        "workflow/ending"
      ]
    },

    // ============================================
    // PLATFORM GUIDES (Restructured & Flattened)
    // ============================================
    {
      type: "category",
      label: "Platform Guides",
      items: [
        "technical-reference/feature-definition",
        {
          type: "category",
          label: "Desktop",
          items: [
            "platform-guides/desktop/desktop-feature-api",
            "platform-guides/desktop/desktop-pref-experiments",
            "platform-guides/desktop/onboarding-feature-desktop",
            "platform-guides/desktop/desktop-migration-guide",
            "platform-guides/desktop/preview",
            "platform-guides/desktop/desktop-incident-response",
            "platform-guides/desktop/desktop-enroll-locally",
            "platform-guides/desktop/desktop-targeting-debug"
          ]
        },
        {
          type: "category",
          label: "Android",
          items: [
            "platform-guides/android/getting-started-for-android-engineers",
            "platform-guides/android/onboarding-feature-android",
            "platform-guides/android/android-microsurveys",
            "platform-guides/android/getting-started-mobile-required-ui",
            "platform-guides/android/android-custom-targeting"
          ]
        },
        {
          type: "category",
          label: "iOS",
          items: [
            "platform-guides/ios/getting-started-for-ios-engineers",
            "platform-guides/ios/onboarding-feature-ios",
            "platform-guides/ios/ios-microsurveys",
            "platform-guides/ios/ios-custom-targeting"
          ]
        },
        {
          type: "category",
          label: "Web (Cirrus)",
          items: [
            "platform-guides/web/getting-started-for-nimbus-web-integration"
          ]
        },
        {
          type: "category",
          label: "Targeting",
          items: [
            "advanced/custom-audiences",
            "advanced/population-sizing",
            "advanced/mobile-behavioral-targeting",
            "advanced/recording-targeting-context-values-to-glean"
          ]
        },
        {
          type: "category",
          label: "Feature Manifest Language (FML)",
          items: [
            "technical-reference/fml/fml-spec",
            "technical-reference/fml/fml-cookbook",
            "technical-reference/fml/fml-front-end-format",
            "technical-reference/fml/fml-string-alias",
            "technical-reference/fml/fml-paths",
            "technical-reference/fml/fml-imports",
            "technical-reference/fml/fml-cli",
            "technical-reference/fml/coenrolling-features",
            "technical-reference/fml/feature-metadata",
            "technical-reference/fml/using-prefs",
            "technical-reference/fml/growable-collections",
            "technical-reference/fml/fm-unimplemented-spec",
            "advanced/feature-variables",
            "advanced/branches-page-deep-dive"
          ]
        },
        {
          type: "category",
          label: "Nimbus CLI (Mobile)",
          items: [
            {
              type: 'autogenerated',
              dirName: "platform-guides/mobile-tools/nimbus-cli"
            }
          ]
        },
        {
          type: "doc",
          label: "Nimbus DevTools (Desktop)",
          id: "resources/nimbus-devtools-guide"
        }
      ]
    },

    // ============================================
    // DATA & ANALYSIS
    // ============================================
    {
      type: "category",
      label: "Data & Analysis",
      items: [
        {
          type: "category",
          label: "Analysis",
          items: [
            "data-analysis/jetstream/overview",
            "data-analysis/jetstream/metrics",
            "data-analysis/jetstream/outcomes",
            "data-analysis/jetstream/statistics",
            "data-analysis/jetstream/configuration"
          ]
        },
        "data-analysis/experiment-sizing",
        "data-analysis/auto-sizing-cli",
        {
          type: "category",
          label: "Data Topics",
          items: [
            "data-analysis/data-topics/bucketing",
            "data-analysis/data-topics/sizing",
            "data-analysis/data-topics/missing_exposures",
            "data-analysis/data-topics/preenrollment_bias",
            "data-analysis/data-topics/population_representativeness",
            "data-analysis/telemetry",
            "data-analysis/validating-experiments"
          ]
        },
        {
          type: "category",
          label: "Jetstream Operations",
          items: [
            "data-analysis/jetstream/operations",
            "data-analysis/jetstream/testing",
            "data-analysis/jetstream/troubleshooting",
            "data-analysis/jetstream/data-products",
            "data-analysis/jetstream/adding-a-platform"
          ]
        },
        {
          type: "link",
          label: "Jetstream GitHub",
          href: "https://github.com/mozilla/jetstream"
        }
      ]
    },

    // ============================================
    // MESSAGING SYSTEM (Flattened)
    // ============================================
    {
      type: "category",
      label: "Messaging System",
      items: [
        "messaging/experiments-and-user-messaging",
        "messaging/desktop/messaging-surfaces",
        "messaging/desktop/display-logic",
        "messaging/desktop/message-configuration",
        "messaging/desktop/message-lifecycle",
        "messaging/desktop/mobile-messaging",
        "messaging/mobile-surveys"
      ]
    },

    // ============================================
    // ADVANCED TOPICS
    // ============================================
    {
      type: "category",
      label: "Advanced Topics",
      items: [
        "advanced/mobile-first-run-experiments",
        "advanced/mobile-enrollment-state-machine",
        "advanced/notificationse",
        "advanced/warnings",
        "advanced/experimenter-state"
      ]
    },

    // ============================================
    // TECHNICAL REFERENCE
    // ============================================
    {
      type: "category",
      label: "Technical Reference",
      items: [
        "technical-reference/system-architecture",
        "technical-reference/client-sdk-states-and-lifecycle",
        "technical-reference/integration-tests"
      ]
    },

    // ============================================
    // FAQ (Consolidated)
    // ============================================
    {
      type: "category",
      label: "FAQ",
      items: [
        "faq/getting-started-faq",
        "faq/experiment-lifecycle-faq",
        "faq/rollouts-faq",
        "faq/targeting-audiences-faq",
        "faq/data-metrics-analysis-faq",
        "faq/platform-specific-faq"
      ]
    },

    // ============================================
    // RESOURCES (Flattened)
    // ============================================
    {
      type: "category",
      label: "Resources",
      items: [
        {
          type: "doc",
          label: "Glossary",
          id: "glossary"
        },
        "resources/foxfooding",
        "resources/local-enrollment",
        {
          type: "category",
          label: "What's New Archive",
          items: [
            {
              type: 'autogenerated',
              dirName: "whats-news/2024"
            },
            {
              type: 'autogenerated',
              dirName: "whats-news/2023"
            },
            {
              type: 'autogenerated',
              dirName: "whats-news/2022"
            },
            {
              type: 'autogenerated',
              dirName: "whats-news/2021"
            }
          ]
        }
      ]
    },

    // ============================================
    // EXTERNAL LINKS
    // ============================================
    {
      type: "category",
      label: "External Links",
      items: [
        {
          type: "link",
          label: "Experimenter GitHub Repo",
          href: "https://github.com/mozilla/experimenter"
        },
        {
          type: "link",
          label: "How to Launch a Nimbus Experiment",
          href: "https://mozilla-hub.atlassian.net/wiki/spaces/FJT/pages/11469776/Nimbus+Onboarding#NimbusOnboarding-LaunchingExperimentsusingNimbus!"
        },
        {
          type: "link",
          label: "Nimbus Data Transfer Object",
          href: "https://mozilla-hub.atlassian.net/wiki/spaces/FJT/pages/11469537/The+Nimbus+Data+Transfer+Object+DTO"
        },
        {
          type: "link",
          label: "Experiment Telemetry",
          href: "https://mozilla-hub.atlassian.net/wiki/spaces/FJT/pages/11469458/Nimbus+Engineering#NimbusEngineering-ExperimentTelemetry"
        },
        {
          type: "link",
          label: "Lessons Learned",
          href: "https://mozilla-hub.atlassian.net/wiki/spaces/FJT/pages/11470136/Lessons+Learned+-+Experiment+Incidents+and+Close+Calls"
        }
      ]
    }
  ]
};
